apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: stagefront
spec:
  type: ExternalName
  externalName: backend-service.stageback.svc.cluster.local
  ports:
    - port: 8080
      targetPort: 8080
