apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: homolfront
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # MUDANÇA CRÍTICA
    nginx.ingress.kubernetes.io/configuration-snippet: |
      try_files $uri $uri/ /index.html;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api  # SÓ O PREFIXO
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80