apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prodfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: heshambr/frontend:latest
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "250Mi"
            limits:
              memory: "1Gi"
              ephemeral-storage: "500Mi"
